spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/sharemusic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  tomcat:
    max-http-form-post-size: 5MB