spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:~/sharemusic;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework.jdbc.core: debug
    org.hibernate.SQL: debug

app:
  host: http://localhost:8080

batchSize: 500
