spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
          cache-private: true
        use-last-modified: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
server:
  tomcat:
    max-http-form-post-size: 5MB
  error:
    whitelabel:
      enabled: false