spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/sharemusic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: DEBUG