spring:
  datasource:
    url: jdbc:h2:~/sharemusic;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
app:
  host: http://localhost:8080

logging:
  level: debug
