spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: debug

server:
  tomcat:
    max-http-form-post-size: 5MB

jwt:
  secret: default
#  error:
#    whitelabel:
#      enabled: false