spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sharemusic
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  tomcat:
    max-http-form-post-size: 5MB