spring:
  profiles:
    include: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
#  web:
#    resources:
#      cache:
#        cachecontrol:
#          max-age: 30d
#        use-last-modified: on
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: /**

logging:
  level:
    org.hibernate.SQL: debug

server:
  tomcat:
    max-http-form-post-size: 5MB
#  error:
#    whitelabel:
#      enabled: false